export default {
  idtransport: {
    auto: [
      {
        key : 'null',
        label: `Je n'ai pas de frais d'automobile à déduire`,
      },
      {
        key : '3CV',
        label: `3 CV`,
        distance: [
          { min: 0, coef: 0.451, ajust: 0 },
          { min: 5000, coef: 0.27, ajust: 906 },
          { min: 20000, coef: 0.315, ajust: 0 },
        ]
      },
      {
        key : '4CV',
        label: "4 CV",
        distance: [
          { min: 0, coef: 0.518, ajust: 0 },
          { min: 5000, coef: 0.291, ajust: 1136 },
          { min: 20000, coef: 0.349, ajust: 0 },
        ]
      },
      {
        key : '5CV',
        label: "5 CV",
        distance: [
          { min: 0, coef: 0.543, ajust: 0 },
          { min: 5000, coef: 0.305, ajust: 1188 },
          { min: 20000, coef: 0.364, ajust: 0 },
        ]
      },
      {
        key : '6CV',
        label: "6 CV",
        distance: [
          { min: 0, coef: 0.568, ajust: 0 },
          { min: 5000, coef: 0.320, ajust: 1244 },
          { min: 20000, coef: 0.382, ajust: 0 },
        ]
      },
      {
        key : '7CV',
        label: "7 CV et plus",
        distance: [
          { min: 0, coef: 0.595, ajust: 0 },
          { min: 5000, coef: 0.337, ajust: 1288 },
          { min: 20000, coef: 0.401, ajust: 0 },
        ]
      },
    ],
    moto: [
      {
        key : 'null',
        label: `Je n'ai pas de frais deux roues à déduire`,
      },
      {
        key : '50',
        label: "< 50cm³",
        distance: [
          { min: 0, coef: 0.269, ajust: 0 },
          { min: 2000, coef: 0.063, ajust: 412 },
          { min: 5000, coef: 0.146, ajust: 0 },
        ]
      },
      {
        key : '2CV',
        label: "1 ou 2 CV",
        distance: [
          { min: 0, coef: 0.338, ajust: 0 },
          { min: 3000, coef: 0.084, ajust: 760 },
          { min: 6000, coef: 0.211, ajust: 0 },
        ]
      },
      {
        key : '5CV',
        label: "3, 4 ou 5 CV",
        distance: [
          { min: 0, coef: 0.4, ajust: 0 },
          { min: 3000, coef: 0.07, ajust: 989 },
          { min: 6000, coef: 0.235, ajust: 0 },
        ]
      },
      {
        key : '6',
        label: "6 CV et plus",
        distance: [
          { min: 0, coef: 0.518, ajust: 0 },
          { min: 3000, coef: 0.067, ajust: 1351 },
          { min: 6000, coef: 0.292, ajust: 0 },
        ]
      },
    ]
  },
  idjournalieres: [
  {
    "pays":"AFGHANISTAN",
    "zone":"L",
    "montant":"242.31",
    "du":""
  },
  {
    "pays":"AFRIQUE DU SUD",
    "zone":"L",
    "montant":"138",
    "du":""
  },
  {
    "pays":"ANGOLA",
    "zone":"L",
    "montant":"300",
    "du":""
  },
  {
    "pays":"ANGUILLA",
    "zone":"L",
    "montant":"180.65",
    "du":""
  },
  {
    "pays":"ANTIGUA",
    "zone":"L",
    "montant":"199.76",
    "du":""
  },
  {
    "pays":"ARABIE SAOUDITE",
    "zone":"L",
    "montant":"158",
    "du":""
  },
  {
    "pays":"ARGENTINE",
    "zone":"L",
    "montant":"136.36",
    "du":""
  },
  {
    "pays":"ARMENIE",
    "zone":"L",
    "montant":"186",
    "du":""
  },
  {
    "pays":"ARUBA",
    "zone":"L",
    "montant":"130.28",
    "du":""
  },
  {
    "pays":"AUSTRALIE",
    "zone":"L",
    "montant":"234.14",
    "du":""
  },
  {
    "pays":"AZERBAIDJAN",
    "zone":"L",
    "montant":"204",
    "du":""
  },
  {
    "pays":"BAHAMAS",
    "zone":"L",
    "montant":"179.78",
    "du":""
  },
  {
    "pays":"BAHREIN",
    "zone":"L",
    "montant":"200",
    "du":""
  },
  {
    "pays":"BANGLADESH",
    "zone":"L",
    "montant":"130",
    "du":""
  },
  {
    "pays":"BARBADE",
    "zone":"L",
    "montant":"269.24",
    "du":""
  },
  {
    "pays":"BELIZE",
    "zone":"L",
    "montant":"153.73",
    "du":""
  },
  {
    "pays":"BENIN",
    "zone":"L",
    "montant":"145",
    "du":""
  },
  {
    "pays":"BERMUDES",
    "zone":"L",
    "montant":"169.01",
    "du":""
  },
  {
    "pays":"BIELORUSSIE",
    "zone":"L",
    "montant":"150",
    "du":""
  },
  {
    "pays":"BOLIVIE",
    "zone":"L",
    "montant":"117.25",
    "du":""
  },
  {
    "pays":"BOTSWANA",
    "zone":"L",
    "montant":"119",
    "du":""
  },
  {
    "pays":"BRESIL ",
    "zone":"L",
    "montant":"216",
    "du":""
  },
  {
    "pays":"BRUNEI DARUSSALAM",
    "zone":"L",
    "montant":"162.31",
    "du":""
  },
  {
    "pays":"BURKINA FASO ",
    "zone":"L",
    "montant":"145",
    "du":""
  },
  {
    "pays":"BURUNDI",
    "zone":"L",
    "montant":"140",
    "du":""
  },
  {
    "pays":"CAMBODGE",
    "zone":"L",
    "montant":"130.28",
    "du":""
  },
  {
    "pays":"CAMEROUN",
    "zone":"L",
    "montant":"120",
    "du":""
  },
  {
    "pays":"CANADA",
    "zone":"L",
    "montant":"178.21",
    "du":""
  },
  {
    "pays":"CAP-VERT",
    "zone":"L",
    "montant":"123.11",
    "du":""
  },
  {
    "pays":"CHILI",
    "zone":"L",
    "montant":"188.47",
    "du":""
  },
  {
    "pays":"CHINE",
    "zone":"L",
    "montant":"232.93",
    "du":""
  },
  {
    "pays":"CHINE (SHANGAI)",
    "zone":"L",
    "montant":"232.93",
    "du":""
  },
  {
    "pays":"COLOMBIE",
    "zone":"L",
    "montant":"152.86",
    "du":""
  },
  {
    "pays":"COMORES",
    "zone":"L",
    "montant":"150",
    "du":""
  },
  {
    "pays":"CONGO",
    "zone":"L",
    "montant":"106.53",
    "du":""
  },
  {
    "pays":"COREE DU NORD",
    "zone":"L",
    "montant":"236.23",
    "du":""
  },
  {
    "pays":"COREE DU SUD",
    "zone":"L",
    "montant":"210",
    "du":""
  },
  {
    "pays":"COSTA RICA",
    "zone":"L",
    "montant":"146.78",
    "du":""
  },
  {
    "pays":"COTE D’IVOIRE",
    "zone":"L",
    "montant":"208.86",
    "du":""
  },
  {
    "pays":"CUBA",
    "zone":"L",
    "montant":"155",
    "du":""
  },
  {
    "pays":"CURAÇAO",
    "zone":"L",
    "montant":"130.28",
    "du":""
  },
  {
    "pays":"DJIBOUTI",
    "zone":"L",
    "montant":"177.93",
    "du":""
  },
  {
    "pays":"DOMINIQUE",
    "zone":"L",
    "montant":"174.57",
    "du":""
  },
  {
    "pays":"EGYPTE",
    "zone":"L",
    "montant":"148",
    "du":""
  },
  {
    "pays":"EMIRATS ARABES UNIS",
    "zone":"L",
    "montant":"300",
    "du":""
  },
  {
    "pays":"EQUATEUR",
    "zone":"L",
    "montant":"130.28",
    "du":""
  },
  {
    "pays":"ERYTHREE",
    "zone":"L",
    "montant":"94",
    "du":""
  },
  {
    "pays":"ETATS - UNIS",
    "zone":"L",
    "montant":"277.92",
    "du":""
  },
  {
    "pays":"ETATS - UNIS (NEW-YORK)",
    "zone":"L",
    "montant":"277.92",
    "du":""
  },
  {
    "pays":"ETATS - UNIS (NEW-YORK)",
    "zone":"L",
    "montant":"390.83",
    "du":"01/09/15"
  },
  {
    "pays":"ETHIOPIE",
    "zone":"L",
    "montant":"123",
    "du":""
  },
  {
    "pays":"FIDJI",
    "zone":"L",
    "montant":"94.68",
    "du":""
  },
  {
    "pays":"GABON",
    "zone":"L",
    "montant":"152.45",
    "du":""
  },
  {
    "pays":"GAMBIE",
    "zone":"L",
    "montant":"52.02",
    "du":""
  },
  {
    "pays":"GEORGIE",
    "zone":"L",
    "montant":"169.36",
    "du":""
  },
  {
    "pays":"GHANA",
    "zone":"L",
    "montant":"166.75",
    "du":""
  },
  {
    "pays":"GRENADE",
    "zone":"L",
    "montant":"172.83",
    "du":""
  },
  {
    "pays":"GRENADINES",
    "zone":"L",
    "montant":"163.28",
    "du":""
  },
  {
    "pays":"GUATEMALA",
    "zone":"L",
    "montant":"160",
    "du":""
  },
  {
    "pays":"GUINEE (CONAKRY)",
    "zone":"L",
    "montant":"170",
    "du":""
  },
  {
    "pays":"GUINEE BISSAU",
    "zone":"L",
    "montant":"105",
    "du":""
  },
  {
    "pays":"GUINEE EQUATORIALE",
    "zone":"L",
    "montant":"137.97",
    "du":""
  },
  {
    "pays":"GUYANA (GEORGETOWN)",
    "zone":"L",
    "montant":"173.7",
    "du":""
  },
  {
    "pays":"HAITI",
    "zone":"L",
    "montant":"191.07",
    "du":""
  },
  {
    "pays":"HONDURAS",
    "zone":"L",
    "montant":"132.01",
    "du":""
  },
  {
    "pays":"HONG-KONG",
    "zone":"L",
    "montant":"246.44",
    "du":""
  },
  {
    "pays":"ILES CAIMAN",
    "zone":"L",
    "montant":"122.46",
    "du":""
  },
  {
    "pays":"ILES COOK",
    "zone":"L",
    "montant":"160.26",
    "du":""
  },
  {
    "pays":"ILES MARSHALL",
    "zone":"L",
    "montant":"133.75",
    "du":""
  },
  {
    "pays":"ILES PALAOS",
    "zone":"L",
    "montant":"270.11",
    "du":""
  },
  {
    "pays":"INDE",
    "zone":"L",
    "montant":"260",
    "du":""
  },
  {
    "pays":"INDONESIE",
    "zone":"L",
    "montant":"160",
    "du":""
  },
  {
    "pays":"IRAK",
    "zone":"L",
    "montant":"300",
    "du":""
  },
  {
    "pays":"IRAN",
    "zone":"L",
    "montant":"161.54",
    "du":""
  },
  {
    "pays":"ISRAEL",
    "zone":"L",
    "montant":"230",
    "du":""
  },
  {
    "pays":"JAMAIQUE",
    "zone":"L",
    "montant":"140.7",
    "du":""
  },
  {
    "pays":"JAPON",
    "zone":"L",
    "montant":"184.58",
    "du":""
  },
  {
    "pays":"JAPON (TOKYO)",
    "zone":"L",
    "montant":"217.16",
    "du":""
  },
  {
    "pays":"JORDANIE",
    "zone":"L",
    "montant":"185.83",
    "du":""
  },
  {
    "pays":"KAZAKHSTAN",
    "zone":"L",
    "montant":"290",
    "du":""
  },
  {
    "pays":"KENYA",
    "zone":"L",
    "montant":"122.46",
    "du":""
  },
  {
    "pays":"KIRGHIZIE",
    "zone":"L",
    "montant":"150",
    "du":""
  },
  {
    "pays":"KIRIBATI",
    "zone":"L",
    "montant":"93.41",
    "du":""
  },
  {
    "pays":"KOWEIT",
    "zone":"L",
    "montant":"245",
    "du":""
  },
  {
    "pays":"LAOS",
    "zone":"L",
    "montant":"130.28",
    "du":""
  },
  {
    "pays":"LESOTHO",
    "zone":"L",
    "montant":"120",
    "du":""
  },
  {
    "pays":"LIBAN",
    "zone":"L",
    "montant":"154",
    "du":""
  },
  {
    "pays":"LIBERIA",
    "zone":"L",
    "montant":"199.76",
    "du":""
  },
  {
    "pays":"LIBYE",
    "zone":"L",
    "montant":"191.88",
    "du":""
  },
  {
    "pays":"MACAO",
    "zone":"L",
    "montant":"246.44",
    "du":""
  },
  {
    "pays":"MADAGASCAR",
    "zone":"L",
    "montant":"114",
    "du":""
  },
  {
    "pays":"MALAISIE",
    "zone":"L",
    "montant":"104.97",
    "du":""
  },
  {
    "pays":"MALAWI",
    "zone":"L",
    "montant":"185.86",
    "du":""
  },
  {
    "pays":"MALDIVES",
    "zone":"L",
    "montant":"230",
    "du":""
  },
  {
    "pays":"MALI",
    "zone":"L",
    "montant":"94.52",
    "du":""
  },
  {
    "pays":"MAURICE",
    "zone":"L",
    "montant":"142.22",
    "du":""
  },
  {
    "pays":"MAURITANIE",
    "zone":"L",
    "montant":"143",
    "du":""
  },
  {
    "pays":"MEXIQUE",
    "zone":"L",
    "montant":"150",
    "du":""
  },
  {
    "pays":"MICRONESIE",
    "zone":"L",
    "montant":"136.36",
    "du":""
  },
  {
    "pays":"MOLDAVIE",
    "zone":"L",
    "montant":"163.28",
    "du":""
  },
  {
    "pays":"MONGOLIE",
    "zone":"L",
    "montant":"102",
    "du":""
  },
  {
    "pays":"MOZAMBIQUE",
    "zone":"L",
    "montant":"164.15",
    "du":""
  },
  {
    "pays":"MYANMAR (BIRMANIE)",
    "zone":"L",
    "montant":"217.13",
    "du":""
  },
  {
    "pays":"NAMIBIE",
    "zone":"L",
    "montant":"90",
    "du":""
  },
  {
    "pays":"NAURU",
    "zone":"L",
    "montant":"87.92",
    "du":""
  },
  {
    "pays":"NEPAL",
    "zone":"L",
    "montant":"121.59",
    "du":""
  },
  {
    "pays":"NICARAGUA",
    "zone":"L",
    "montant":"133.75",
    "du":""
  },
  {
    "pays":"NIGER",
    "zone":"L",
    "montant":"118.91",
    "du":""
  },
  {
    "pays":"NIGERIA",
    "zone":"L",
    "montant":"273",
    "du":""
  },
  {
    "pays":"NIUE",
    "zone":"L",
    "montant":"129.74",
    "du":""
  },
  {
    "pays":"NOUVELLE CALEDONIE",
    "zone":"L",
    "montant":"120",
    "du":""
  },
  {
    "pays":"NOUVELLE ZELANDE",
    "zone":"L",
    "montant":"235.31",
    "du":""
  },
  {
    "pays":"OMAN",
    "zone":"L",
    "montant":"265",
    "du":""
  },
  {
    "pays":"OUGANDA",
    "zone":"L",
    "montant":"130",
    "du":""
  },
  {
    "pays":"OUZBEKISTAN",
    "zone":"L",
    "montant":"98.14",
    "du":""
  },
  {
    "pays":"PAKISTAN",
    "zone":"L",
    "montant":"150.25",
    "du":""
  },
  {
    "pays":"PANAMA",
    "zone":"L",
    "montant":"154.59",
    "du":""
  },
  {
    "pays":"PAPOUASIE NOUVELLE GUINEE",
    "zone":"L",
    "montant":"172",
    "du":""
  },
  {
    "pays":"PARAGUAY",
    "zone":"L",
    "montant":"156.33",
    "du":""
  },
  {
    "pays":"PEROU",
    "zone":"L",
    "montant":"147.65",
    "du":""
  },
  {
    "pays":"PHILIPPINES",
    "zone":"L",
    "montant":"166.36",
    "du":""
  },
  {
    "pays":"POLYNESIE FRANÇAISE",
    "zone":"L",
    "montant":"120",
    "du":""
  },
  {
    "pays":"QATAR",
    "zone":"L",
    "montant":"278",
    "du":""
  },
  {
    "pays":"REP CENTRAFRICAINE ",
    "zone":"L",
    "montant":"121.96",
    "du":""
  },
  {
    "pays":"REPUBLIQUE DEM DU CONGO",
    "zone":"L",
    "montant":"195",
    "du":""
  },
  {
    "pays":"REPUBLIQUE DOMINICAINE",
    "zone":"L",
    "montant":"109.52",
    "du":""
  },
  {
    "pays":"REP DU SOUDAN SUD",
    "zone":"L",
    "montant":"265.76",
    "du":""
  },
  {
    "pays":"REPUBLIQUE DU YEMEN",
    "zone":"L",
    "montant":"188",
    "du":""
  },
  {
    "pays":"RUSSIE",
    "zone":"L",
    "montant":"230",
    "du":""
  },
  {
    "pays":"RWANDA",
    "zone":"L",
    "montant":"240.58",
    "du":""
  },
  {
    "pays":"SAINT-KITTS-ET-NEVIS",
    "zone":"L",
    "montant":"175.44",
    "du":""
  },
  {
    "pays":"SAINT-VINCENT",
    "zone":"L",
    "montant":"163.28",
    "du":""
  },
  {
    "pays":"SAINTE-LUCIE",
    "zone":"L",
    "montant":"172.83",
    "du":""
  },
  {
    "pays":"SALVADOR",
    "zone":"L",
    "montant":"153.73",
    "du":""
  },
  {
    "pays":"SAMOA OCCIDENTALES",
    "zone":"L",
    "montant":"120.72",
    "du":""
  },
  {
    "pays":"SAO TOME-ET-PRINCIPE",
    "zone":"L",
    "montant":"117.25",
    "du":""
  },
  {
    "pays":"SENEGAL",
    "zone":"L",
    "montant":"139.95",
    "du":""
  },
  {
    "pays":"SEYCHELLES",
    "zone":"L",
    "montant":"300",
    "du":""
  },
  {
    "pays":"SIERRA LEONE",
    "zone":"L",
    "montant":"225.81",
    "du":""
  },
  {
    "pays":"SINGAPOUR",
    "zone":"L",
    "montant":"200",
    "du":""
  },
  {
    "pays":"SOMALIE",
    "zone":"L",
    "montant":"137.22",
    "du":""
  },
  {
    "pays":"SOUDAN",
    "zone":"L",
    "montant":"151.99",
    "du":""
  },
  {
    "pays":"SRI LANKA",
    "zone":"L",
    "montant":"155",
    "du":""
  },
  {
    "pays":"SURINAM",
    "zone":"L",
    "montant":"156.33",
    "du":""
  },
  {
    "pays":"SWAZILAND",
    "zone":"L",
    "montant":"41.95",
    "du":""
  },
  {
    "pays":"SYRIE",
    "zone":"L",
    "montant":"154",
    "du":""
  },
  {
    "pays":"TADJIKISTAN",
    "zone":"L",
    "montant":"117.25",
    "du":""
  },
  {
    "pays":"TAIWAN",
    "zone":"L",
    "montant":"160.83",
    "du":""
  },
  {
    "pays":"TANZANIE",
    "zone":"L",
    "montant":"135",
    "du":""
  },
  {
    "pays":"TCHAD",
    "zone":"L",
    "montant":"225",
    "du":""
  },
  {
    "pays":"THAILANDE",
    "zone":"L",
    "montant":"98.16",
    "du":""
  },
  {
    "pays":"TIMOR ORIENTAL",
    "zone":"L",
    "montant":"150",
    "du":""
  },
  {
    "pays":"TOGO",
    "zone":"L",
    "montant":"125.98",
    "du":""
  },
  {
    "pays":"TONGA",
    "zone":"L",
    "montant":"90.46",
    "du":""
  },
  {
    "pays":"TRINITE ET TOBAGO",
    "zone":"L",
    "montant":"231.89",
    "du":""
  },
  {
    "pays":"TURKMENISTAN",
    "zone":"L",
    "montant":"102",
    "du":""
  },
  {
    "pays":"TURQUIE",
    "zone":"L",
    "montant":"165",
    "du":""
  },
  {
    "pays":"TUVALU",
    "zone":"L",
    "montant":"81.16",
    "du":""
  },
  {
    "pays":"UKRAINE",
    "zone":"L",
    "montant":"208",
    "du":""
  },
  {
    "pays":"URUGUAY",
    "zone":"L",
    "montant":"117.25",
    "du":""
  },
  {
    "pays":"VANUATU",
    "zone":"L",
    "montant":"210",
    "du":""
  },
  {
    "pays":"VENEZUELA",
    "zone":"L",
    "montant":"195",
    "du":""
  },
  {
    "pays":"VIETNAM",
    "zone":"L",
    "montant":"158",
    "du":""
  },
  {
    "pays":"WALLIS ET FUTUNA",
    "zone":"L",
    "montant":"120",
    "du":""
  },
  {
    "pays":"ZAMBIE",
    "zone":"L",
    "montant":"180",
    "du":""
  },
  {
    "pays":"ZIMBABWE",
    "zone":"L",
    "montant":"156.33",
    "du":""
  },
  {
    "pays":"ALBANIE",
    "zone":"E",
    "montant":"180",
    "du":""
  },
  {
    "pays":"ALGERIE",
    "zone":"E",
    "montant":"99.07",
    "du":""
  },
  {
    "pays":"BOSNIE-HERZEGOVINE",
    "zone":"E",
    "montant":"169",
    "du":""
  },
  {
    "pays":"BULGARIE",
    "zone":"E",
    "montant":"145",
    "du":""
  },
  {
    "pays":"CROATIE",
    "zone":"E",
    "montant":"142",
    "du":""
  },
  {
    "pays":"DANEMARK",
    "zone":"E",
    "montant":"222.7",
    "du":""
  },
  {
    "pays":"GRANDE-BRETAGNE",
    "zone":"E",
    "montant":"171.87",
    "du":""
  },
  {
    "pays":"HONGRIE",
    "zone":"E",
    "montant":"175",
    "du":""
  },
  {
    "pays":"ISLANDE",
    "zone":"E",
    "montant":"101.66",
    "du":""
  },
  {
    "pays":"LIECHTENSTEIN",
    "zone":"E",
    "montant":"201.23",
    "du":""
  },
  {
    "pays":"MACEDOINE",
    "zone":"E",
    "montant":"117",
    "du":""
  },
  {
    "pays":"MAROC",
    "zone":"E",
    "montant":"175",
    "du":""
  },
  {
    "pays":"MONTENEGRO",
    "zone":"E",
    "montant":"150",
    "du":""
  },
  {
    "pays":"NORVEGE",
    "zone":"E",
    "montant":"157.15",
    "du":""
  },
  {
    "pays":"POLOGNE",
    "zone":"E",
    "montant":"175",
    "du":""
  },
  {
    "pays":"REPUBLIQUE TCHEQUE",
    "zone":"E",
    "montant":"180",
    "du":""
  },
  {
    "pays":"ROUMANIE",
    "zone":"E",
    "montant":"160",
    "du":""
  },
  {
    "pays":"SERBIE",
    "zone":"E",
    "montant":"150",
    "du":""
  },
  {
    "pays":"SUEDE",
    "zone":"E",
    "montant":"214.93",
    "du":""
  },
  {
    "pays":"SUISSE",
    "zone":"E",
    "montant":"201.23",
    "du":""
  },
  {
    "pays":"TUNISIE",
    "zone":"E",
    "montant":"125",
    "du":""
  },
  {
    "pays":"ALLEMAGNE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"BELGIQUE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"CHYPRE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"ESPAGNE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"ESTONIE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"FINLANDE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"FRANCE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"GRÈCE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"GUADELOUPE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"GUYANE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"IRLANDE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"ITALIE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"LA RÉUNION",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"LETTONIE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"LITUANIE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"LUXEMBOURG",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"MALTE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"MARTINIQUE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"MAYOTTE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"PAYS-BAS",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"PORTUGAL",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"SAINT BARTHÉLÉMY",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"SAINT-MARTIN",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"SAINT PIERRE ET MIQUELON",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"SLOVAQUIE",
    "zone":"E",
    "montant":"156",
    "du":""
  },
  {
    "pays":"SLOVÉNIE",
    "zone":"E",
    "montant":"156",
    "du":""
  }
  ]
}
